### ISSUE TITLE
Missing sort by

### ISSUE THREAD

**Issue by sen1** [bengalspice/Codecademy-Data-Analytics#1]
https://github.com/bengalspice/Codecademy-Data-Analytics/blob/01440e4d48c2902da6f0f99d31f2edfce2c181aa/Protected%20Species#L11-L13

Code looks great but as instructed it is missing sort by. The correct answer is 
```
protection_counts = species.groupby('conservation_status')\
    .scientific_name.nunique().reset_index()\
    .sort_values(by='scientific_name')
```

**Comment by bengalspice** [comment]
It's correct in the zip file.
