### ISSUE TITLE
Boolean column

### ISSUE THREAD

**Issue by sen1** [bengalspice/Codecademy-Data-Analytics#3]
https://github.com/bengalspice/Codecademy-Data-Analytics/blob/01440e4d48c2902da6f0f99d31f2edfce2c181aa/Observations%20of%20Sheep#L13

You already have a boolean column species.is_sheep where values are True/False. if you do `species.is_sheep==True`, it does not gain anything for you. So I would do:
species[species.is_sheep]

**Comment by bengalspice** [comment]
The zip file has the correct version of the code.
