### ISSUE TITLE
Wrong result

### ISSUE THREAD

**Issue by sen1** [bengalspice/Codecademy-Data-Analytics#4]
https://github.com/bengalspice/Codecademy-Data-Analytics/blob/01440e4d48c2902da6f0f99d31f2edfce2c181aa/Observations%20of%20Sheep#L38-L44

With baseline 15 and minimum detectable effect of 33.3%, you will need sample size of 510. https://www.optimizely.com/sample-size-calculator/?conversion=15&effect=33.3&significance=90

Hence:
bryce = 510 / 250.
yellowstone = 510 / 507.

# Approximately 2 weeks at Bryce and 1 week at Yellowstone.

**Comment by bengalspice** [comment]
I guess because I used just 33 it gave me a larger sample size. I had this issue with doing the project on Codecademy. 

The correct file is in the zip. The directions were to zip the final project, so that is what I did.
