### ISSUE TITLE
Summary

### ISSUE THREAD

**Issue by sen1** [bengalspice/Codecademy-Data-Analytics#5]
Great work! I probably won’t have much to say here because you pretty much nailed it all the way through.

Your Python work was excellent and very readable. There are a couple points where your code could be accomplished a bit more efficiently, but everything worked the way it was supposed to. Except the sample size your got all the answers correctly.

Presentation: I couldn't find your presentation. I didnt look into your zip file but your were supposed to put in the same directory.

Excellent work overall.

**Comment by bengalspice** [comment]
The slides were uploaded with the jupyter notebook file. I can upload it separately.

**Comment by bengalspice** [comment]
I think you looked at the wrong files. You should have looked at the one marked capstone. The other files were cut and paste from Codecademy.
