### ISSUE TITLE
(Summary) Exceeds expectations

### ISSUE THREAD

**Issue by CharlesDLandau** [bengalspice/Codecademy-Data-Analytics#6]
Well done! Despite some stylistic notes and a few notes I had for hopefully making the code more "pythonic," you are spot-on. Your findings and your ability to communicate them are the critical components here, and you did well in both categories.

In terms of improvement I've already pointed out PEPs 20 and 8, and I would definitely recommend that you sit with them. You may be ready to dive in with PyPi and teach yourself a new library - make it yours and become an expert!

If you'd like to go deeper on this project, you could recruit some friends/family to run through your presentation (this helps work out the rough edges and you get practice talking about your data and findings. Always important.)

Congratulations on finishing the class!

**Comment by bengalspice** [comment]
Thank you!

**Comment by CharlesDLandau** [comment]
You're very welcome, well done! Congratulations on finishing the class!
