### ISSUE TITLE
(Plotting) Careful with .show()!

### ISSUE THREAD

**Issue by CharlesDLandau** [bengalspice/Codecademy-Data-Analytics#7]
Be careful when calling savefig after show - it looks like it was fine here, but I've seen students run into trouble with that - it can clear the list of fig and ax objects, for instance.

https://github.com/bengalspice/Codecademy-Data-Analytics/blob/f428ed092f33445b94c751ff6bd6c744aa5dca4d/musclehub.py#L383-L384

**Comment by bengalspice** [comment]
Thank you. I will take more care about using plt.show when it's not needed for the overall code to run.

**Comment by CharlesDLandau** [comment]
Even if it is needed, calling it as late in the sequence as possible has gotten me better results.
