### ISSUE TITLE
(Practices) Adhere to PEP-20

### ISSUE THREAD

**Issue by CharlesDLandau** [bengalspice/Codecademy-Data-Analytics#8]
Remember PEP-20 and adhere to it. Hardcoding these values makes the overall plotting less flexible and takes longer than necessary - it's the sort of thing a list comprehension does really well too. For the first one you can simply do

`[i/10 for i in range(0, 11)]`

And for the second we can do: 

`
[r"{}%".format(x) for x in range(0, 101, 10)]
`

Linking those parameters to other values in your process would then become trivial, plus you saved yourself the trouble of having to hard-code the values.

https://github.com/bengalspice/Codecademy-Data-Analytics/blob/f428ed092f33445b94c751ff6bd6c744aa5dca4d/musclehub.py#L396-L397

**Comment by bengalspice** [comment]
Thank you for this suggestion. I'm still learning all the shortcuts for how to make my code more elegant.

**Comment by CharlesDLandau** [comment]
It takes time! You're already writing good code, and putting the polish on is easier to learn than getting the right answer.
